# 2.0 Technologies and Tools

- [2.0 Technologies and Tools](#20-technologies-and-tools)
  - [2.1 Install and configure network components, both hardware and software-based, to support organizational security.](#21-install-and-configure-network-components-both-hardware-and-software-based-to-support-organizational-security)
    - [2.1.1 Firewall](#211-firewall)
    - [2.1.2 VPN concentrator](#212-vpn-concentrator)
    - [2.1.3 NIPS/NIDS](#213-nipsnids)
    - [2.1.4 Router](#214-router)
    - [2.1.5 Switch](#215-switch)
    - [2.1.6 Proxy](#216-proxy)
    - [2.1.7 Load balancer](#217-load-balancer)
    - [2.1.8 Access point](#218-access-point)
    - [2.1.9 SIEM: Security Information and Event Management](#219-siem-security-information-and-event-management)
    - [2.1.10 DLP: Data Loss Prevention](#2110-dlp-data-loss-prevention)
    - [2.1.11 NAC: Network Access Control](#2111-nac-network-access-control)
    - [2.1.13 Bridge](#2113-bridge)
    - [2.1.14 SSL/TLS accelerators](#2114-ssltls-accelerators)
    - [2.1.15 SSL decryptors](#2115-ssl-decryptors)
    - [2.1.16 Hardware security module (HSM)](#2116-hardware-security-module-hsm)
    - [2.1.17 Media gateway](#2117-media-gateway)
  - [2.2 Given a scenario, use appropriate software tools to assess the security posture of an organization.](#22-given-a-scenario-use-appropriate-software-tools-to-assess-the-security-posture-of-an-organization)
    - [2.2.1 Protocol analyzer](#221-protocol-analyzer)
    - [2.2.2 Network scanners](#222-network-scanners)
    - [2.2.3 Wireless scanners/cracker](#223-wireless-scannerscracker)
    - [2.2.4 Password cracker](#224-password-cracker)
    - [2.2.5 Vulnerability scanner](#225-vulnerability-scanner)
    - [2.2.6 Configuration compliance scanner](#226-configuration-compliance-scanner)
    - [2.2.7 Exploitation frameworks](#227-exploitation-frameworks)
    - [2.2.8 Data sanitization tools](#228-data-sanitization-tools)
    - [2.2.9 Steganog  raphy tools](#229-steganog--raphy-tools)
    - [2.2.10 Honeypot](#2210-honeypot)
    - [2.2.11 Backup utilities](#2211-backup-utilities)
    - [2.2.12 Banner grabbing](#2212-banner-grabbing)
    - [2.2.13 Passive vs. active](#2213-passive-vs-active)
    - [2.2.14 Command line tools](#2214-command-line-tools)
  - [2.3 Given a scenario, troubleshoot common security issues.](#23-given-a-scenario-troubleshoot-common-security-issues)
  - [2.4 Given a scenario, analyze and interpret output from security technologies.](#24-given-a-scenario-analyze-and-interpret-output-from-security-technologies)
  - [2.5 Given a scenario, deploy mobile devices securely.](#25-given-a-scenario-deploy-mobile-devices-securely)
    - [2.5.1 Connection methods](#251-connection-methods)
    - [2.5.2 Mobile device management (MDM) concepts](#252-mobile-device-management-mdm-concepts)
    - [2.5.3 Enforcement and monitoring](#253-enforcement-and-monitoring)
    - [2.5.4 Deployment models](#254-deployment-models)
  - [2.6 Given a scenario, implement secure protocols.](#26-given-a-scenario-implement-secure-protocols)

## 2.1 Install and configure network components, both hardware and software-based, to support organizational security. 
([Mike Meyers 1](https://www.udemy.com/course/comptia-security-certification-sy0-501-the-total-course/learn/lecture/9826954#overview), [Mike Meyers 2](https://www.udemy.com/course/comptia-security-certification-sy0-501-the-total-course/learn/lecture/9826972#overview))

### 2.1.1 Firewall
 ([James Messer](https://www.youtube.com/watch?v=mDKKqPxMpb0&list=PL5ysgoFoCpZEM8cboeHdRDePc2bOU9CN1&index=43))
  - Keeps bad traffic from coming in; sometimes from leaving too
  - Controls traffic flow
  - Content control as well
    - Inappropriate content
    - Malware
  - The three basic types of firewalls are packet filtering, circuit-level gateway, and application-level gateway. A fourth type combines features from these three and is called a stateful inspection firewall.(Stewart)
  - ACL , Access control lists
    - Rules for allow/disallow
    - Usually validate the rules from top to bottom
    - "Access control lists (ACLs) are lists of users and their permitted actions." (Conklin) 
  - Application-based vs. network-based
    - Network based firewalls 
      - Is a hardware device, typically called an appliance
      - Provide broad protection for an entire Network
      - Filter traffic by port number OSI layer 4 (TCP/UDP) , modern firewalls support L7
      - Mostly L:3 devices (routers), usually sits on the ingress/egress of the network
    - Application-based firewalls (aka application-layer firewalls) 
      - Can be a device, server addon, virtual service or a system filter
      - can analyze traffic at an even deeper level, examining the application characteristics of traffic and blocking specific actions while allowing others, even inside web-connected applications. This gives application-based firewalls much greater specificity than network-based firewalls that only look at IP addresses and ports." (Conklin)
      - Controls traffic flows based on application (SQL server/ browser)
      - Used with IPS
      - Host based firewalls
  - Stateful vs. stateless
    - Stateless
      - Doesn't keep track of sessions, only use ACL to allow or disallow
      - Act as a Packet filter, each packet is individually examined regardless of the past history
      - Need ACL rules for inbound and outbound traffic
    - Stateful
      - Keep track of what traffic flows are active
      - Only need one rule on ACLs, firewall automatically make a session table with source / destination and port number
      - "A stateful packet inspection firewall can act upon the state condition of a conversation—is this a new conversation or a continuation of a conversation, and did it originate inside or outside the firewall?" (Conklin)

  - Implicit deny
    - Implicit deny is the default security stance that says if you aren’t specifically granted access to or privileges for a resource, you’re denied access by default.(Stewart) 
    - Most firewalls include deny at the bottom (if traffic is not specified with the ACL it will be denied)
    - Prevents "any traffic from passing that is not specifically recognized as allowed." (Conklin)
### 2.1.2 VPN concentrator 
([James Messer](https://www.youtube.com/watch?v=sxBQZQM-RNk&list=PL5ysgoFoCpZEM8cboeHdRDePc2bOU9CN1&index=44))
  - VPN concentrator 

    - A VPN concentrator is a dedicated hardware device designed to support a large number of simultaneous VPN connections, often hundreds or thousands. It provides high availability, high scalability, and high performance for secure VPN connections.(Stewart)
    - A device thats use to encrypt and decrypt VPN traffic, often integrated in to a firewall
    - Deployed as specialized cryptographic hardware or software based options
  - Remote access vs. site-to-site
    - Remote access VPN (tunnel) have On-demand access from a remote device (PC VPN software to VPN concentrator)
    - Site to site VPN are usually always on
    - "When the VPN is set up to connect specific machines between two networks on an ongoing basis, with no setup per communication required, it is referred to as a site-to-site VPN configuration. If the VPN connection is designed to allow remote hosts to connect to a network, they are called remote access VPNs." (Conklin)
  - IPSec (Internet protocol security) ([Mike Meyers](https://www.udemy.com/course/comptia-security-certification-sy0-501-the-total-course/learn/lecture/9827094#overview))
    - IPSec is a security architecture framework that supports secure communication over IP. IPSec establishes a secure channel in either transport mode or tunnel mode. It can be used to establish direct communication between computers or to set up a VPN between networks.(Stewart)
    - Authentication and encryption for every packet. (OSI L3)
    - Confidentiality and Integrity check/ Anti-replay
    - Two different modes of communication ([Image1](https://i.imgur.com/k9YzvLM.png), [Image2](https://imgur.com/h784FZ8))
      - Transport mode
        - Data is encrypted
        - IPSec headers and trailers
        - Original IP header used
        - Typically used for remote-access VPN.
      - Tunnel mode
        - Both IP header and data are encrypted
        - Completely different IP header put on front of packet
        - Typically used for site-to-site VPN. 

    -  Two core IPSec protocols (two methods for implementing IPsec) [Image](https://imgur.com/pyp5KjO)
       - AH: Authentication header
         - Provide integrity 
         - AH is the Hash of the packet (IP Header + Data) plus shared key( MD5/SHA1/2) 
         - "The AH, when added to an IP datagram, ensures the integrity of the data and also the authenticity of the data’s origin." (Conklin)
       - ESP: Encapsulating Security Payload
         - Provide confidentiality and Integrity
         - ESP provides encryption of the transferred data as well as limited authentication.(Stewart)
         - "Provides security services for the higher-level protocol portion of the packet only, not the IP header." (Conklin)
  - Split tunnel vs. full tunnel
    - "Split tunnel is a form of VPN where not all traffic is routed via the VPN." (Conklin)
    - "A full tunnel solution routes all traffic over the VPN, providing protection to all networking traffic." (Conklin)
  - TLS ([Mike Meyers](https://www.udemy.com/course/comptia-security-certification-sy0-501-the-total-course/learn/lecture/9827352#overview))
    - "TLS-based VPNs have some advantages over IPSec-based VPNs when networks are heavily NAT encoded, because IPSec-based VPNs can have issues crossing multiple NAT domains." (Conklin)
  - Always-on VPN
    - They use "pre-established connection parameters and automation. Always-on VPNs can self-configure and connect once an Internet connection is sensed and provide VPN functionality without user intervention." (Conklin)
### 2.1.3 NIPS/NIDS 
([James Messer](https://www.youtube.com/watch?v=hEgWPWIuq_s&list=PL5ysgoFoCpZEM8cboeHdRDePc2bOU9CN1&index=45), [Jason Dion 1](https://www.udemy.com/program/comptia-security/learn/2015076/lecture/13214946#overview), [Jason Dion 2](https://www.udemy.com/program/comptia-security/learn/2015076/lecture/13219720#overview), [Mike Meyers](https://www.udemy.com/course/comptia-security-certification-sy0-501-the-total-course/learn/lecture/9827100#overview))
  - Both NIDS / NIPS watch network traffic 
  - Detection - Alarm or Alert
  - Prevention - Stop it before it gets in to the network
  - Inline vs. passive
    - Passive
      - No way to block traffic
      - Receives copy of traffic (port mirror/ SPAN, network trap)
      - Isn't sitting in middle of traffic
      - When malicious traffic is detected IPS can send TCP RST (reset) frames , this is called Out of band response
      - Out-of-band response 
        - After-the-fact malicious traffic detected
        - Sends TCP RST (reset), closes connection
        - limited capability, UPD doesn't allow reset
    - Inline
      - Traffic passes through
      - May be dropped
      - Response is In-band response which is immediate 
  - Identification technologies
    - Signature-based
      - Look for a perfect match
    - Anomaly
      - Build a baseline of what's normal
  - Heuristic/behavioral
    - Use artificial intelligence to identify
  - Rules
    - Block, allow, sent alert, etc.
  - Analytics
    - False positive
      - False alarm
      - e.g. quarantining sites, files which are legitimate
    - False negative
      - Should have been caught, but passed
      - Malicious traffic not identified
### 2.1.4 Router 
([James Messer](https://www.youtube.com/watch?v=I7Tmo1RgF3E&list=PL5ysgoFoCpZEM8cboeHdRDePc2bOU9CN1&index=46), [Jason Dion](https://www.udemy.com/program/comptia-security/learn/2015076/lecture/13140486#overview))
  - A router forwards traffic between IP subnets
  - Layer 3 devices
    - They make decisions on the network level on the OSI model
    - Typically "layer 2" is referring to a switch
    - Routers inside of switches sometimes called "layer 3 switches"
    - Often connects diverse network types (LAN/WAN/copper / fiber)
  - ACLs: Access Control Lists
    - Used by routers, firewalls and switches 
    - Used to allow or deny traffic (also used for NAT, QA)
    - Can be configured on ingress or egress of an interface
    - Evaluate traffic on certain criteria
      - Source IP, destination IP, TCP port numbers, UDP port numbers, ICMP
    - "The ACLs should be deployed on the routers. The ACLs will improve network security by confining sensitive data traffic to computers on a specific subnet. By implementing ACLs and rules, you can ensure that a secure router configuration is implemented, which will protect the routers and the subnets they manage." (uCertify)
  - Antispoofing
    - Prevent others from using someone else's address
    - Man-in-the-middle, DDoS
    - router can Filter reserved IP addresses (RFC 1918 should not be open to the internet)
    - RPF: Reverse Path Forwarding
      - The response to an inbound packet should return the same way
      - If it doesn't, then drop the packet right now
### 2.1.5 Switch
 ([James Messer](https://www.youtube.com/watch?v=I7Tmo1RgF3E&list=PL5ysgoFoCpZEM8cboeHdRDePc2bOU9CN1&index=46), [Jason Dion](https://www.udemy.com/program/comptia-security/learn/2015076/lecture/13140484#overview))
  - OSI layer 2 device
    - Uses MAC address based forwarding
  - Bridging done in hardware ASIC: Application-specific integrated circuit
  - Port security
    - Inside of network less secure
    - IEEE 802.1X - Port-based Network Access Control (NAC)
      - You don't get access until you authenticate
      - Makes extensive use of EAP and RADIUS
      - Physical ports (not TCP/UDP)
      - Administrative enable/disable unused ports
      - Duplicate MAC address checking
        - Stop the spoofers
  - "A switch can reduce network traffic on a particular network segment. It does this by keeping a table of information about computers on that segment. Instead of broadcasting information to all ports of the switch, the switch selectively chooses where the information goes." (uCertify)
  - Loop prevention
    - Two switches connected together will send traffic back and forth forever
    - Easy way to take down a network
    - STP: Spanning Tree Protocol
      - 802.1D
      - Prevents loops
  - Flood guard
    - Configure a maximum number of MAC addresses on an interface
    - Configure specific MAC addresses
  - Layer 2 vs. Layer 3
    - Layer 3 switches
      - Switching operates at OSI layer 2
      - Routing still operates at OSI layer 3
### 2.1.6 Proxy
 ([James Messer](https://www.youtube.com/watch?v=I7yyVNQzRuo&list=PL5ysgoFoCpZEM8cboeHdRDePc2bOU9CN1&index=47), [Mike Meyers](https://www.udemy.com/course/comptia-security-certification-sy0-501-the-total-course/learn/lecture/9827076#overview))
  - A proxy server is a variation of an application-level firewall or circuit-level firewall. A proxy server is used as a proxy or middleman between clients and servers.(Stewart 
  - Receives the user requests and sends the request on their behalf (the proxy)
  - Useful for caching information, access control, URL filtering, content scanning
  - Modes of operation
    - Explicit proxy
      - OS or browser must be configured to explicitly use proxy
    - Transparent
      - Invisible; end users have no idea there is a proxy in the middle
  - Application proxies (most common)
    - The proxy understands the way the application works
    - NAT (network address translation)
      - Network-level proxy
      - One of the simplest proxies
    - Some proxies may only know one application (e.g. HTTP)
    - Other proxies are multipurpose proxies
      - HTTP, HTTPS, FTP
  - Forward and reverse proxy (different ways proxies can operate)
    - Forward proxy [image](https://imgur.com/DgzBVB1)
      - An "internal proxy"
        - Commonly used to protect and control internal user access to the internet
    - Reverse proxy [image](https://imgur.com/5OxZ9qR)
      - Inbound traffic from the internet to your interal service (e.g web server)
  - Open proxy
    - A third-party, uncontrolled proxy
      - Can be a significant security concern (owners can add malicious code)
      - Often used to circumvent existing security controls (e.g URL filtering)
### 2.1.7 Load balancer 
([James Messer](https://www.youtube.com/watch?v=NHhuVpD6LyU&list=PL5ysgoFoCpZEM8cboeHdRDePc2bOU9CN1&index=48))
  - Distributes the load
    - Multiple service
    - Invisible to the end-user
  - Large scale implementations
    - Web server farms, database farms
  - Fault tolerance
    - Server outages have no effect
    - Very fast convergence
  - SSL offload
    - Encryption/decryption
  - Caching
    - Fast response  
  - Prioritization
    - QoS Quality of service, some applications get priority 
  - Content switching
    - Application centric balancing, (different number of servers based on the application )
  - How traffic is Scheduled to go to different servers
    - Round-robin
      - Each server is selected in turn
      - Dynamic round-robin
        - Distribute load to server with lowest use
      - Weighted round-robin
        - Prioritize the server use (some servers might get more traffic)
    - Affinity
      - Since loadbalancer sending traffic to different server each time, its challenging for some applications to maintain the session
      - Uses the same server for a particular user or instance
      - Tracked through IP address or session IDs
  - Active-active
    - All servers are active, request can send to these servers at any time
  - Active-passive
    - Some servers available
    - Others on standby
    - Passive servers take place of failed servers
  - Virtual IPs
    - "Allow for multiple systems to be reflected back as a single IP address." (Conklin)
### 2.1.8 Access point
 ([James Messer](https://www.youtube.com/watch?v=-I3KAqMQljo&list=PL5ysgoFoCpZEM8cboeHdRDePc2bOU9CN1&index=49))
  - Not a wireless router
    - A wireless router is a router and a WAP in a single device
    - WAP is a bridge
      - Extends the wired network onto the wireless network
      - An OSI layer 2 device
  - SSID: Service Set Identifier
    - Name of the wireless network
    - Change the SSID to something not-so obvious
  - Disabled SSID broadcasting?
    - This was never designed to be a wireless security feature
    - SSID easily determined through wireless network analysis
    - Security through obscurity - not recommended 
  - IEEE Standards for wireless networks 
    - 802.11 is the IEEE standard for wireless network communications. 
    - Versions include 802.11a (2 Mbps), 802.11b (11 Mbps), 802.11g (54 Mbps) and 802.11n (150+ Mbps).
    - The 802.11 standard also defines Wired Equivalent Privacy (WEP).
  - MAC filtering
    - Limit access to only certain physical devices
    - Keep neighbors out of AP
    - But MAC addresses can be spoofed
      - Use packet-capturing device to discern MAC address
  - Signal strength
    - Power level controls
      - Limit power of signal
      - Set it as low as possible
    - "The power levels will dictate how far an access point can transmit its signal. For more coverage, increase the power levels, but be careful not to go beyond your organization's work area, or other neighboring entities might try to compromise your network." (uCertify)
  - Band selection/width
    - Throughput
      - Maximum theoretical throughputs (because its hard to determine the actual value)
      - Actual throughput can vary
    - Frequency
      - 2.4 GHz and 5 GHz 
      - Sometimes both
  - Band selection and Bandwidth
      - 2.4 GHz frequency is more crowded - 3 non overlapping IEEE channels, 1,6,11 - all 3 are 20 MHz
      - 5 GHz has much larger spectrum (ranging from 20 MHz to 160 MHz)


  - Antenna types and placement
    - Omnidirectional antennas
      - Most common
      
